version: "3.9"  # optional since v1.27.0
services:
  app:
    build: .
    volumes:
      - ./src:/mnt/host/src
      - ~/develop/dataset/kitti/kitti_for_pointpillar/kitti/testing/velodyne:/mnt/host/dataset
    tty: true
